### ISSUE TITLE
Intermittent connection

### ISSUE THREAD

**Issue by lasry1** [andyb2000/HACS-husqvarna_automower_ble#12]
Hello again!

the automower sensors seem to be offline quite often and i was wondering if this is related to my BT gateway and i should add another one only for this active connection without scanning for other stuff (i have many BT plant sensors and 3 gateways around my house)

how’s your sensors looking? Are they stable?

On a separate note, is there anything i could do to contribute to this project? If i am of any help i would love to do it

Thanks again!

![image](https://github.com/user-attachments/assets/18d71b80-505a-4029-b6cf-4e22a6640b07)

**Comment by andyb2000** [comment]
Hi,
Unfortunately this seems common, my sensors do the same thing, I suspect it's due to how the Flymo mower does it's bluetooth (Often the official app can't connect or takes time to connect).

I'm not sure how we can improve this at this time as it's down to the underlying library, so I suspect adding more bluetooth proxies won't help (For example, overnight mine is practically beside the bluetooth ESP32 and it still drops off).

What I could look to do is write a 'cache' into the component for HASS so that it doesn't go into unavailable all the time, just leaves the last value on and only if it doesn't communicate for a while it goes unavailable. 
I may look into this if I get time this week.

**Comment by lasry1** [comment]
Hello!

That was my thought, waiting over 5 or 10 minutes before the status gets updated as 'unavailable' and up to that time retrieves the last known value.

It isn't ideal but at least it filters all that data.

**Comment by andyb2000** [comment]
I've merged my test code for this in #16 which now caches (up to 1hr) the connection so the entities shouldn't keep going offline when the bluetooth connection drops and comes back.

**Comment by lasry1** [comment]
that's great thanks Andy!

To be fair the mower sensor doesn't go offline too often it's more with the other sensors.

Sorry a bit off topic but will the new joined PR from the Alastair's repo be also updated automatically to your repo? (I added the GO 150 to the models and it has been merged)

**Comment by lasry1** [comment]
Hi again!

For some reason the update doesn't show up on my HACS. Weird, i can see you changed the version to 0.0.9 but the one i have installed is the 0.0.5

Do you happen to know why? is the version also in other parts of the code? 
<img width="1363" alt="Screenshot 2024-07-24 at 09 30 09" src="https://github.com/user-attachments/assets/d83a977b-e615-4faf-86a2-30bbad2f7883">

**Comment by andyb2000** [comment]
I'd not pushed the git release, I keep forgetting! apologies. should work now.

**Comment by lasry1** [comment]
thank you Andy! it showed up however now all sensors are keeping the value but the mower itself becomes unavailable intermittently as before. That's intended right? so we know at that particular point the mower isn't available

**Comment by andyb2000** [comment]
Yes that's sort of intended, I didn't want to cache the main mower/controls so it's clear when the BLE connection is down, as I'm unsure if sending a mow/park (for people with mowers that do respond) when the BLE was down would cause an issue.
I think for now it's the safer option.
As it's down to the underlying communications and library I'm going to close this issue as it's not specifically with the HACS integration.
